# FROM ubuntu:latest
FROM gcc:latest

# COPY . /usr/src/cpp_test

RUN curl -O https://swaroopjoshi.in/courses/csf111-sp22/

WORKDIR /usr/src/assignment

# RUN g++ Account.cpp Transaction.cpp SimpleClasses.cpp > log_file.txt 2>&1

# CMD ./a.out
